### ISSUE TITLE
Error On Openshift When Attempting To Deploy

### ISSUE THREAD

**Issue by kamikazechaser** [maxired/openshift-ubuntu-cartridge#1]
FIXED

**Comment by maxired** [comment]
Hey,

this hack is several years old and since then, lot happen on openshift. 
Frorm what i understand, you can know run docker container on top of openshift, so there should be better way to do that now.

Anyway, sorry, but I won't be able to provide you support for that ;)

**Comment by kamikazechaser** [comment]
Alright So OpenShift Online NewGen has some problems importing images as seen [here](http://stackoverflow.com/questions/38457982/importing-docker-images-images-from-the-public-registry-into-openshift/38513855#38513855)
